sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mkerins/mass .
  - docker run -d mkerins/mass /bin/sh -c "freshclam && /etc/init.d/clamav-daemon start"

install:
  - pip install codecov

script:
  - docker run -d mkerins/mass /bin/sh -c "./run_tests"

after_success:
  - codecov
