# ref: https://docs.travis-ci.com/user/languages/python
language: python
dist: trusty

matrix:
    include:
     - python: 3.6
       env: TOXENV=py36
     - python: 3.6
       env: TOXENV=flake8

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov
