sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t mkerins/mass .
  - docker run -d carlad/sinatra /bin/sh -c "freshclam && /etc/init.d/clamav-daemon start"

script:
  - ./run_tests

after_success:
  - codecov
