version: '3'

services:
  # TODO: set up supervisord to handle rqworker
  web:
    build:
      context: .
    command: ./run_prod.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: mass.settings.prod
  redis:
    image: redis
    ports:
      - "6379:6379"
