version: '3'

services:
  web:
    build:
      context: .
    command: ./run_web.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: foobar1
      POSTGRES_USER: mass
      POSTGRES_DB: mass
